### ISSUE TITLE
.abi not generated

### ISSUE THREAD

**Issue by hart87a** [ZoroChain/Zoro-Contracts#1]
Hey, I'm not sure where else to ask this but I'm trying to get your NFT template to work on a private network and I'm almost there - I've got the .avm file to load on my neo-gui but it's unconfirmed, and on further inspection the .abi that's generated is blank. 

I'm getting the output:
```
1>  NFTContract -> C:\Users\Aaron\Documents\GitHub\Zoro-Contracts\NFT\NFTContract\bin\Release\NFTContract.dll
1>  Start NeoContract converter, Source File: C:\Users\Aaron\Documents\GitHub\Zoro-Contracts\NFT\NFTContract\bin\Release\NFTContract.dll
1>  Neo.Compiler.MSIL console app v2.4.1.0
1>  Find entrypoint:System.Object NFTContract.NFTContract::Main(System.String,System.Object[])
1>  convert succ
1>CONVERTTASK : gen abi error : System.NullReferenceException: Object reference not set to an instance of an object.
1>     at vmtool.FuncExport.ConvType(String _type) in C:\Users\Aaron\Documents\GitHub\neo-devpack-dotnet\src\Neo.Compiler.MSIL\FuncExport.cs:line 60
1>     at vmtool.FuncExport.Export(NeoModule module, Byte[] script) in C:\Users\Aaron\Documents\GitHub\neo-devpack-dotnet\src\Neo.Compiler.MSIL\FuncExport.cs:line 166
1>     at Neo.Compiler.Program.Main(String[] args) in C:\Users\Aaron\Documents\GitHub\neo-devpack-dotnet\src\Neo.Compiler.MSIL\Program.cs:line 94
1>  write:NFTContract.avm
1>  write:NFTContract.abi.json
1>  SUCC
```

Do you have any idea how to fix this and generate the json? Do I just have a conflicting branch of the neo-compiler?

Thanks for any advice!

**Comment by ProDog** [comment]
Your neo-compiler and Neo.SmartContract.Framework should have the same version,And it's configured correctly,check it，reference:https://docs.neo.org/en-us/sc/quickstart/getting-started-csharp.html
